project:
  name: FlashBench
  version: 1

dependencies:
  - flatbuffers

input_path:
  - input_data/proj_0.yaml
  # Add more YAML file paths here as needed
  # - /path/to/proj_2.yaml
  # - /path/to/proj_3.yaml


output_dir: output

profile_verbose: True

enable_splitkv: True
