project:
  name: FlashBench
  version: '1.0'

dependencies:
  - flatbuffers
  - tqdm

input_path:
  - input_data/flash_attn_func_params.yaml
  # Add more YAML file paths here as needed
  # - /path/to/proj_2.yaml
  # - /path/to/proj_3.yaml

kernels_file: ./kernel_traits_condidates.yaml

output_dir: output

profile_verbose: True

# if not specified, all grid types will be tested 
grid_types:
  - 4
  - 5

# if not specified, all balance types will be tested 
balance_types:
  - 0

platform: MXC500
