project:
  name: FlashBench
  version: '1.0'

logging:
  log_level: DEBUG  # Can be DEBUG, INFO, WARNING, ERROR, or CRITICAL
  flash_attn_log_enable: 0
  flash_attn_log_level: 3
  flash_attn_log_file: False

dependencies:
  - flatbuffers
  - tqdm

input_path:
  - input_data/flash_attn_params.yaml
  # Add more YAML file paths here as needed


kernels_file: ./kernel_traits_candidates.yaml

output_dir: output

profile_verbose: False

platform: MXC500
