mha_api: "flash_attn_func"

mha_params:
  # deepseek
  - head_dim_qk: 128
    head_dim_v: 128
    num_heads_q: 56
    num_heads_kv: 56
    batch_size: 2
    seqlens_q:
      - 4096
      - 4096
    seqlens_kv:
      - 4096
      - 4096
    dtype: bfloat16
    dropout: false
    causal: true
    alibi: false
    window_left: -1
    window_right: -1
    attn_mask: false
    deterministic: false
    paged_kv: false
    is_training: true

  # opensora
  - head_dim_qk: 72
    head_dim_v: 72
    num_heads_q: 16
    num_heads_kv: 16
    batch_size: 128
    seqlens_q:
      - 900
    seqlens_kv:
      - 900
    dtype: bfloat16
    dropout: false
    causal: false
    alibi: false
    window_left: -1
    window_right: -1
    attn_mask: false
    deterministic: false
    paged_kv: false
    is_training: true
  
  # deepseek_v2
  - head_dim_qk: 256
    head_dim_v: 256
    num_heads_q: 16
    num_heads_kv: 16
    batch_size: 256
    seqlens_q:
      - 8
    seqlens_kv:
      - 8
    dtype: bfloat16
    dropout: false
    causal: true
    alibi: false
    window_left: -1
    window_right: -1
    attn_mask: false
    deterministic: false
    paged_kv: false
    is_training: false

  # llama2-70B
  - head_dim_qk: 128
    head_dim_v: 128
    num_heads_q: 8
    num_heads_kv: 8
    batch_size: 1
    seqlens_q:
      - 4096
    seqlens_kv:
      - 4096
    dtype: bfloat16
    dropout: false
    causal: true
    alibi: false
    window_left: -1
    window_right: -1
    attn_mask: false
    deterministic: true
    paged_kv: false
    is_training: true

  # shuanchuangyuan
  - head_dim_qk: 128
    head_dim_v: 128
    num_heads_q: 8
    num_heads_kv: 8
    batch_size: 1
    seqlens_q:
      - 4096
    seqlens_kv:
      - 4096
    dtype: bfloat16
    dropout: false
    causal: true
    alibi: false
    window_left: -1
    window_right: -1
    attn_mask: false
    deterministic: true
    paged_kv: false
    is_training: true

  # shuanchuangyuan
  - head_dim_qk: 128
    head_dim_v: 128
    num_heads_q: 8
    num_heads_kv: 8
    batch_size: 1
    seqlens_q:
      - 2048
    seqlens_kv:
      - 2048
    dtype: bfloat16
    dropout: false
    causal: true
    alibi: false
    window_left: -1
    window_right: -1
    attn_mask: false
    deterministic: true
    paged_kv: false
    is_training: true

  # opensora
  - head_dim_qk: 72
    head_dim_v: 72
    num_heads_q: 16
    num_heads_kv: 16
    batch_size: 60
    seqlens_q:
      - 3600
    seqlens_kv:
      - 3600
    dtype: float16
    dropout: false
    causal: false
    alibi: false
    window_left: -1
    window_right: -1
    attn_mask: false
    deterministic: false
    paged_kv: false
    is_training: false

  # gpt moe 576B
  - head_dim_qk: 128
    head_dim_v: 128
    num_heads_q: 8
    num_heads_kv: 8
    batch_size: 1
    seqlens_q:
      - 4096
    seqlens_kv:
      - 4096
    dtype: bfloat16
    dropout: false
    causal: true
    alibi: false
    window_left: -1
    window_right: -1
    attn_mask: false
    deterministic: true
    paged_kv: false
    is_training: true

  # baichuan2-7B
  - head_dim_qk: 128
    head_dim_v: 128
    num_heads_q: 32
    num_heads_kv: 32
    batch_size: 1
    seqlens_q:
      - 4096
    seqlens_kv:
      - 4096
    dtype: bfloat16
    dropout: true
    causal: true
    alibi: false
    window_left: -1
    window_right: -1
    attn_mask: false
    deterministic: false
    paged_kv: false
    is_training: true

  # easyllm-20B
  - head_dim_qk: 128
    head_dim_v: 128
    num_heads_q: 16
    num_heads_kv: 16
    batch_size: 1
    seqlens_q:
      - 32768
    seqlens_kv:
      - 32768
    dtype: bfloat16
    dropout: false
    causal: true
    alibi: false
    window_left: -1
    window_right: -1
    attn_mask: false
    deterministic: false
    paged_kv: false
    is_training: true

  # deepseek_v2
  - head_dim_qk: 192
    head_dim_v: 128
    num_heads_q: 16
    num_heads_kv: 16
    batch_size: 1
    seqlens_q:
      - 4096
    seqlens_kv:
      - 4096
    dtype: bfloat16
    dropout: false
    causal: true
    alibi: false
    window_left: -1
    window_right: -1
    attn_mask: false
    deterministic: false
    paged_kv: false
    is_training: true
