mha_api: "flash_attn_with_kvcache"

mha_params:
  - head_dim: 128
    num_heads_q: 8
    num_heads_kv: 8
    batch_size: 4
    seqlens_q:
      - 1
    seqlens_kv:
      - 239
    dtype: bfloat16
    causal: true
    alibi: false
    window_left: -1
    window_right: -1
    paged_kv: false
    append_kv: false
    is_training: false
