mha_api: "flash_attn_with_kvcache"

mha_params:
  - head_dim: 128
    num_heads_q: 8
    num_heads_kv: 8
    batch_size: 1
    paged_block_size: 256
    paged_num_blocks: 1
    seqlens_q:
      - 1
    dtype: bfloat16
    causal: true
    alibi: false
    window_left: -1
    window_right: -1
    paged_kv: true
    append_kv: false
    is_training: false
